# Настройки приложения
server:
    port: 7788 # порт веб сервера томкат на котором принимаются запросы от клиента
    fileSize: 1 # размерность в Гб
    fileDir: "src/main/resources/file" # Путь где размещаются сгенерированные тестовые файлы