//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.10.06 at 05:47:07 AM MSK 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://chumarin.ru/ws/findNumber", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package ru.chumarin.ws.findnumber;
